[package]
name = "oxitortoise"
version = "0.1.0"
edition = "2021"

[dependencies]
derive_more = { version = "1.0.0", features = ["full"] }
either = "1.15.0"
flagset = "0.4.6"
slotmap = "1.0.7"

[features]
runtime-unsafety = []

[[bin]]
name = "ants"
path = "bench/models/ants/wasm.rs"
