[package]
name = "lir"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_more = { version = "2.0.1", features = ["full"] }
smallvec = "1.15.1"
typed-index-collections = "3.3.0"
walrus = "0.23.3"
